### ISSUE TITLE
Idea (and will this app work tomorrow...?)

### ISSUE THREAD

**Issue by captaincrunch93** [eshapard/AnkiHRPG#15]
Hey, just started using your app today, and it's unbelievably good. Was actually just coming on here to see if there's a way of getting anki ticket off as a daily on habitica, as anki is a bit of a daily activity, and it'd be great if that could come up on habtica! (in addition to points for reviews) Just an idea, don't know if you think it's any good!

In regards to a previous thread, I saw about downloading from github or ankiweb, I downloaded from ankiweb, does that mean i'm running a past version? And will the app stop working tomorrow or has the code been upgraded for the new API?

Cheers!

**Comment by eshapard** [comment]
Thanks Cap'n!

I have a daily for Anki too, so I may create an option for marking off a
daily if you've done some arbitrary number of habits that day... but I
haven't worked on that yet.

If you downloaded the addon through ankiweb, then you have the current
stable version. I am working on a version 2.0 that will hopefully blow your
socks off, but that new version is still experimental.

They say they're going to discontinue the v2 API for Habatica on July 15,
so the version you have will work until then.

I should have the new version (which uses the new v3 API) out and posted to
ankiweb by then. I think it'll actually prompt you to upgrade the addon.

**Comment by captaincrunch93** [comment]
Quickest reply out! thanks for that it all sounds great, and my bad on the time of discontinuing of the API, read it as june on one of the other forums so thought i'd started using this at the exact wrong time!

Cheers

**Comment by eshapard** [comment]
Hey Captain,

I wrote a small script to add marking a daily Anki habit as complete. You just need to drop it in the AnkiHabitica subdirectory of your Anki addons folder and edit the config section to set it up.

https://github.com/eshapard/AnkiHabitica/blob/master/extras/daily_habit.py

**Comment by captaincrunch93** [comment]
Hey eshapard,

Looks great (and thanks so much for doing this!) just had one problem though, i'm using the version of this downloaded from the anki add on website, and i don't seem to have a AnkiHabitica subdirectory in my add ons folder (just the python file there) Is this just for the new version 2 of the add-on?

Cheers

**Comment by eshapard** [comment]
Yeah, it's for v2.
