### ISSUE TITLE
Sync to AnkiWeb failure

### ISSUE THREAD

**Issue by Caspid** [eshapard/AnkiHRPG#4]
Syncing failed: 'HTTP Error 503: Service Unavailable'

**Comment by OVenkur** [comment]
I have the same problem: syncing to Ankiweb fail with 'HTTP Error 401: Unauthorized'.
It happen AFTER configuring, if I remove `.habitrpg.conf`and restart Anki all works good (except for HRPG).

Kubuntu 15.04, python 2.7.9/3.4.3 (not sure which one is used by Anki).

**Comment by OVenkur** [comment]
Ok, it's not a problem of addon, but HabitRPG documentation. User Data Display show `User ID` while `API Token ` is empty and commentary say: "Your API Token is a password". From this informtation I thought it's my account password, but correct data is on the page:
https://habitrpg.com/#/options/settings/api

**Comment by eshapard** [comment]
Thanks for figuring that out. HabitRPG (Habitica) is constantly changing,
so the API section (and url) will probably change in the future.

**Comment by sheldon1232** [comment]
Hey there this same problem is happening to me and i try the proper user ID and API token but still not working... your help would be much appreciated 

Im using a mac El Capitan 10.11.3 and the latest version of anki

**Comment by sheldon1232** [comment]
'HTTP Error 401: Unauthorized' Thats the response i get...

**Comment by eshapard** [comment]
401: Unauthorized sounds like habitica did not accept your userID / api
token.

Try using your userID and APIToken at https://habitica.com/static/api
see if you can download your history using the Try it Out button under
export/history ... or pretty much any of the other options.

Also open the .habitrpg.conf file in your anki addons directory and confirm
that "token" is set to your api token and "user" is set to your userID (not
your avatar name).

**Comment by sheldon1232** [comment]
I used the userID and APIToken on the recommend site to export/history using the try it out button and it worked. However I do not know where the conf file is, I can only find the .py file.

**Comment by eshapard** [comment]
It should be in the same directory as the .py file. It could be a hidden
file on your system. It's called .habitrpg.conf.

Lookup how to list hidden files in your OS. From the command prompt in
linux (ls -a). Mac should also have the ls command, so ls -a should work
too. Windows would be dir /a.

If the file isn't there, try running tools > Setup HabitRPG from the anki
menu again.

**Comment by sheldon1232** [comment]
Hello I have done as suggested and I have found the file. Everything seems to be correct however I still get the same response. 

BTW: Thank you for helping figure this issue out :)

**Comment by eshapard** [comment]
Well I'm pretty much stumped. Have you tried deleting the config file?

**Comment by sheldon1232** [comment]
Yes I have. It is really frustrating as everything seems to be good but the issue is still coming up:(

**Comment by sheldon1232** [comment]
Anything else I could possibly try ?

**Comment by eshapard** [comment]
Maybe one last thing. Delete the contents of the .py file and replace with
the version on github.

**Comment by eshapard** [comment]
I just got this message for the first time. Updating the plugin to use the new habitica.com url instead of habitrpg.com seemed to fix the issue.

I made the change to the github version. Will update the version on Anki's servers.
