### ISSUE TITLE
What is the name of the addon?

### ISSUE THREAD

**Issue by ooker777** [eshapard/AnkiHRPG#5]
Is it *AnkiHRPG* or just *AnkiRPG*?

**Comment by eshapard** [comment]
In the Anki Addons directory, it's named AnkiHRPG

**Comment by ooker777** [comment]
So, should we keep its name be consistency?

**Comment by eshapard** [comment]
Do I refer to it as ankirpg somewhere?

**Comment by ooker777** [comment]
Yes, on the [introduction page] and on the 'Tools" menu in Anki.

**Comment by eshapard** [comment]
OK. I'll see about changing that. I had called it ankirpg at first, but
then I found there was already a plugin by that name.
