### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by ooker777** [eshapard/AnkiHRPG#6]
I give the addon my ID and Token. There is a message say that it will setup thing for me. But in HabitRPG there is no new task.

**Comment by eshapard** [comment]
You won't see any tasks created until you earn points and it will only update HabitRPG when you perform a sync. Have you set up Anki to sync with AnkiWeb?

Try this:
Sync HabitRPG with the sync button.
Open an empty deck or a deck that you've completed; one where you'll get the 'Congratulations, You've finished this deck for now' message in Anki.
Go back to the list of decks screen in Anki and press the 'Synchronize with AnkiWeb' button.
Now Sync HabitRPG and see if it tells you that you've earned some points.

**Comment by ooker777** [comment]
It works, better than I though 😁. From level 3, I'm raised to level 14 😁

I would suggest you to add the instruction into your first page. Also, alarm visitors that they will be leveled up surprisingly.
