### ISSUE TITLE
Does it work on AnkiDroid ?

### ISSUE THREAD

**Issue by ThrashAbaddon** [eshapard/AnkiHRPG#7]
First of all, thank you for making the addon. 
Now I was wondering does it work on android phone because on mine it doesn't? The app is [AnkiDroid](https://play.google.com/store/apps/details?id=com.ichi2.anki).

**Comment by eshapard** [comment]
I don't think it can work on anki droid. I don't know much about the droid
platform, but I would guess that it's too different.
