### ISSUE TITLE
Crashing at anki launch

### ISSUE THREAD

**Issue by meli2905** [eshapard/AnkiHRPG#8]
Traceback (most recent call last):
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.addons", line 41, in loadAddons
  File "c:\pyi\iu.py", line 436, in importHook
  File "c:\pyi\iu.py", line 521, in doimport
  File "C:\Users\DELL\Documents\Anki\addons\Anki_HRPG.py", line 36, in <module>
    api_token = config['token']
KeyError: 'token'

**Comment by eshapard** [comment]
So this happens when you start Anki, or does it happen when you sync or
open a deck or something?

Had you gone through the setup procedure first? It seems to be complaining
about not finding your api_token.

Do you have a .habitrpg.conf file in your Anki addons directory? If so, try
deleting it and then start Anki.

**Comment by meli2905** [comment]
It happens when I start anki. I had just set it up when it chrashed... several times. I deleted the file and it still crashed. 

I give up, deleted the add on :( 

Sorry for responding so late. Very busy with work on this month.

**Comment by eshapard** [comment]
Hmm... sorry about that. It still sounds like it was unhappy with a config
file somehow, but I guess we'll never know.

**Comment by ThrashAbaddon** [comment]
I have that problem, the same traceback

**Comment by eshapard** [comment]
I'm unable to replicate this.

Does this happen immediately after installing the addon, or after you went
to Tools > Setup HabitRPG

What version of Anki is this?
What platform are you running this on? (windows 7, 8, 10, etc.)

Have you tried deleting the .habitrpg.conf file from your Anki addons dir?

Would you mind posting the contents of the .habitrpg.conf file? You can
delete all but the first few digits of your user ID and API key. I want to
check the file to see if it has the "token" set. That's what the error
message is complaining about.

**Comment by ThrashAbaddon** [comment]
Deleting .habitrpg.conf file from Anki addons dir solved the problem. Before that I couldn't enter ID or API because there was no Setup HabitRPG button under Tools tab.

Thank you eshapard :)

**Comment by spottygurgle** [comment]
I get this message when I open Anki on my Macbook:

Traceback (most recent call last):
  File "aqt/addons.pyc", line 41, in loadAddons
  File "/Users/me/Documents/Anki/addons/Anki_HRPG.py", line 36, in <module>
KeyError: 'token'

I don't know if I did something wrong? I'm really dumb with computer stuff. :(

**Comment by eshapard** [comment]
This looks like the same error as the original poster and ThrashAbaddon, spottygurgle.

Have you tried deleting the .habitrpg.conf file from your Anki addons dir?
That should be /Users/me/Documents/Anki/addons/.habitrpg.conf

**Comment by spottygurgle** [comment]
Hi! Thanks for responding! There is only a file called Anki_HRPG.py there.

**Comment by spottygurgle** [comment]
Oh wait I figured it out lol! So embarrassing... Thanks! :)
