### ISSUE TITLE
AnkiDroid Sync with Desktop/HabitPRG

### ISSUE THREAD

**Issue by tazinachka** [eshapard/AnkiHRPG#9]
Hello!

First of all, thank you for creating such a useful add-on!!

I was hoping you could tell me if there is a way to sync the AnkiDroid with the desktop application. I need the whiteboard feature as well as the pinch-zoom gesture, which is only available through the android app ( if you know of the add-on for desktop, I'm all ears!), so I'm forced to use my android tablet.

However, when I sync my tablet with my computer and then refresh HabitRPG I get no new points, despite going through an appreciable amount of cards on the android tablet.

Please let me know if this will be a feature for this add-on, or if you can offer any suggestions.

Thank you!!

**Comment by eshapard** [comment]
Sorry, syncing points like that can't be done.

**Comment by npretto** [comment]
Couldn't the add on save the number of correct answers and on the next sync check for differences?

**Comment by eshapard** [comment]
It already saves the correct answer score to a file.

**Comment by eshapard** [comment]
But of course the plugin does not run in Android... That's not just a
different platform, it's a different programming language; one I don't know.

**Comment by npretto** [comment]
So if i do 10 cards on the phone, and then sync the desktop client which has the add-on it will fire the habitica events?

**Comment by eshapard** [comment]
No. The plugin can't track what you do on the phone. Sorry.

**Comment by eshapard** [comment]
OK, I think I know what you were suggesting. That that plugin do a search for the total number of questions answered / answered correctly, then do the same after syncing with the server and compare.

If possible, that would work... assuming you only have the plugin installed on one computer. If you had the plugin installed on more than one computer, you would end up getting double-scored for questions.

It may be possible to query Anki's database for this, but I don't know enough about Anki's database structure. This would be a major change to the way the plugin works, and I don't think it's worth it to me to investigate, but I'll keep it in mind.

If you can figure out the code to do this, I'd appreciate that.

**Comment by eshapard** [comment]
I did some poking around in the anki database. There's no running counter of times correctly answered. However, for each card you get a reps count (number of times that card has been seen, I think) and the current and previous interval.

So it would be possible to sum up the reps for all cards to get a count of how many times cards have been shown, but not a count of how many correct responses there were.

It would probably be possible to sum the total number of reps for all cards and use that number to score an 'ankidroid rep' habit for every X number of extra reps on the server.

That might work best as a separate function accessed from a dropdown menu.
